name: Scala CI

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  producerBuild:
    name: Build Producer
    runs-on: ubuntu-latest
    steps:
      - name: Build Producer
        uses: actions/checkout@v2
      - run: cd producer && sbt compile
  producerTest:
    needs: producerBuild
    name: Test Producer
    runs-on: ubuntu-latest
    steps:
      - name: Test Producer 
        uses: actions/checkout@v2
      - run: cd producer && sbt test
  consumerBuild:
    name: Build Consumer
    runs-on: ubuntu-latest
    steps:
      - name: Build Consumer
        uses: actions/checkout@v2
      - run: cd consumer && sbt compile
  consumerTest:
    needs: consumerBuild
    name: Test consumer
    runs-on: ubuntu-latest
    steps:
      - name: Test Conmsumer
        uses: actions/checkout@v2
      - run: cd consumer && sbt test
